fixtures:
  forge_modules:
    augeas: "puppetlabs/augeas_core"
    epel: "puppet/epel"
    facter: "ghoneycutt/facter"
    firewalld: "puppet/firewalld"
    stdlib: "puppetlabs/stdlib"
    yumrepo: "puppetlabs/yumrepo_core"
