---
.gitignore:
  paths:
    - .rerun.json
    - .librarian
    - .kitchen
    - .tmp
    - .bundle
    - bolt.log
    - Puppetfile.lock
    - modules
.gitlab-ci.yml:
  # we don't use GitLab
  unmanaged: true
.travis.yml:  
  # we don't use Travis
  unmanaged: true
appveyor.yml:
  # we don't use Appveyor
  unmanaged: true
Gemfile:
spec/spec_helper.rb:
  # rspec mock is preferred, mocha was old (according to puppetlabs_spec_helper/CHANGELOG.md)
  mock_with: ':rspec'
  strict_level: ':warning'
  spec_overrides:
    # print out really long exception messages (this prevents them from being truncated)
    - 'RSpec::Support::ObjectFormatter.default_instance.max_formatted_output_length = 999_999_999'
